apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::076887163641:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-19VMU1NNKQJHT
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::076887163641:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-15T11:54:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1640"
  uid: e30c5062-75f0-4e19-a512-997247163cc4
